import { Category, Product, SoupAddOn, PortionSize, SpiceLevel } from "@/types/soup";

export const CATEGORIES: Category[] = [
  {
    id: "soap",
    name: "ZEVA JEE™ Soap Collection",
    slug: "soap-collection",
    description: "Handcrafted botanical soaps inspired by nature for daily skincare.",
    icon: "🧼",
  },
];

export const ADD_ONS: SoupAddOn[] = [
  { id: "soap-saver", name: "Eco Soap Saver Bag", price: 2.5, category: "Side" },
  { id: "wooden-tray", name: "Sandalwood Soap Dish", price: 8.0, category: "Side" },
  { id: "travel-pouch", name: "Linen Travel Pouch", price: 5.0, category: "Side" },
  { id: "herbal-sachet", name: "Botanical Sachet", price: 3.5, category: "Side" },
];

export const SIZE_MULTIPLIERS: Record<PortionSize, number> = {
  BOWL_8OZ: 1,
  BOWL_16OZ: 1.75,
  FAMILY_32OZ: 3.2,
};

export const PRODUCTS: Product[] = [
  {
    id: "neem",
    name: "Neem Soap",
    slug: "neem-soap",
    tagline: "With Neem Leaf Powder & Neem Oil",
    description: "A refreshing herbal soap suitable for everyday cleansing.",
    basePrice: 9.5,
    imageEmoji: "🌿",
    categoryId: "soap",
    dietaryTags: ["Organic"],
    availableSizes: ["BOWL_8OZ", "BOWL_16OZ", "FAMILY_32OZ"],
    allowSpiceCustomization: false,
    macros: { calories: 0, protein: 0, carbs: 0, fat: 0 },
    attributes: { richness: 70, umami: 0, aromatics: 85, spiceBase: 10 },
    pairings: ["Daily Care", "Herbal Ritual"],
  },
  {
    id: "charcoal",
    name: "Charcoal Soap",
    slug: "charcoal-soap",
    tagline: "With Activated Charcoal & Tea Tree Oil",
    description: "A deep-cleansing soap that leaves your skin feeling fresh.",
    basePrice: 10.5,
    imageEmoji: "🖤",
    categoryId: "soap",
    dietaryTags: ["Gluten-Free"],
    availableSizes: ["BOWL_8OZ", "BOWL_16OZ", "FAMILY_32OZ"],
    allowSpiceCustomization: false,
    macros: { calories: 0, protein: 0, carbs: 0, fat: 0 },
    attributes: { richness: 80, umami: 0, aromatics: 65, spiceBase: 5 },
    pairings: ["Deep Clean", "Activated Charcoal"],
  },
  {
    id: "turmeric",
    name: "Turmeric Soap",
    slug: "turmeric-soap",
    tagline: "With Turmeric & Almond Oil",
    description: "A gentle soap for a clean and naturally refreshed feel.",
    basePrice: 10.0,
    imageEmoji: "✨",
    categoryId: "soap",
    dietaryTags: ["Organic"],
    availableSizes: ["BOWL_8OZ", "BOWL_16OZ", "FAMILY_32OZ"],
    allowSpiceCustomization: false,
    macros: { calories: 0, protein: 0, carbs: 0, fat: 0 },
    attributes: { richness: 75, umami: 0, aromatics: 90, spiceBase: 5 },
    pairings: ["Brightening Ritual", "Gentle Care"],
  },
  {
    id: "lemon",
    name: "Lemon Soap",
    slug: "lemon-soap",
    tagline: "With Lemon Peel Powder & Lemon Essential Oil",
    description: "Leaves the skin feeling fresh with a clean citrus fragrance.",
    basePrice: 9.0,
    imageEmoji: "🍋",
    categoryId: "soap",
    dietaryTags: ["Vegan"],
    availableSizes: ["BOWL_8OZ", "BOWL_16OZ", "FAMILY_32OZ"],
    allowSpiceCustomization: false,
    macros: { calories: 0, protein: 0, carbs: 0, fat: 0 },
    attributes: { richness: 65, umami: 0, aromatics: 95, spiceBase: 5 },
    pairings: ["Citrus Fresh", "Morning Ritual"],
  },
  {
    id: "orange",
    name: "Orange Soap",
    slug: "orange-soap",
    tagline: "With Orange Peel Powder & Orange Essential Oil",
    description: "Provides a refreshing cleansing experience with a naturally vibrant citrus aroma.",
    basePrice: 9.0,
    imageEmoji: "🍊",
    categoryId: "soap",
    dietaryTags: ["Vegan"],
    availableSizes: ["BOWL_8OZ", "BOWL_16OZ", "FAMILY_32OZ"],
    allowSpiceCustomization: false,
    macros: { calories: 0, protein: 0, carbs: 0, fat: 0 },
    attributes: { richness: 68, umami: 0, aromatics: 93, spiceBase: 5 },
    pairings: ["Sunrise Glow", "Daily Cleanse"],
  },
  {
    id: "licorice",
    name: "Licorice Soap",
    slug: "licorice-soap",
    tagline: "With Licorice Root Powder",
    description: "Crafted with botanical ingredients for daily care.",
    basePrice: 11.0,
    imageEmoji: "🌾",
    categoryId: "soap",
    dietaryTags: ["Organic"],
    availableSizes: ["BOWL_8OZ", "BOWL_16OZ", "FAMILY_32OZ"],
    allowSpiceCustomization: false,
    macros: { calories: 0, protein: 0, carbs: 0, fat: 0 },
    attributes: { richness: 72, umami: 0, aromatics: 78, spiceBase: 5 },
    pairings: ["Botanical Balance", "Calming Care"],
  },
  {
    id: "rice",
    name: "Rice Soap",
    slug: "rice-soap",
    tagline: "With Fine Rice Powder",
    description: "Leaves the skin feeling smooth and comfortable.",
    basePrice: 10.0,
    imageEmoji: "🌾",
    categoryId: "soap",
    dietaryTags: ["Gluten-Free"],
    availableSizes: ["BOWL_8OZ", "BOWL_16OZ", "FAMILY_32OZ"],
    allowSpiceCustomization: false,
    macros: { calories: 0, protein: 0, carbs: 0, fat: 0 },
    attributes: { richness: 70, umami: 0, aromatics: 85, spiceBase: 5 },
    pairings: ["Silky Texture", "Daily Luxury"],
  },
  {
    id: "flaxseed",
    name: "Flaxseed Soap",
    slug: "flaxseed-soap",
    tagline: "With Flaxseed Powder",
    description: "A nourishing soap for everyday use.",
    basePrice: 11.5,
    imageEmoji: "🌿",
    categoryId: "soap",
    dietaryTags: ["Vegan", "Organic"],
    availableSizes: ["BOWL_8OZ", "BOWL_16OZ", "FAMILY_32OZ"],
    allowSpiceCustomization: false,
    macros: { calories: 0, protein: 0, carbs: 0, fat: 0 },
    attributes: { richness: 78, umami: 0, aromatics: 82, spiceBase: 5 },
    pairings: ["Nourishing Care", "Daily Comfort"],
  },
  {
    id: "aloe-vera",
    name: "Aloe Vera Soap",
    slug: "aloe-vera-soap",
    tagline: "With Aloe Vera Extract",
    description: "Provides a fresh and soothing cleansing experience.",
    basePrice: 10.5,
    imageEmoji: "🌱",
    categoryId: "soap",
    dietaryTags: ["Vegan", "Dairy-Free"],
    availableSizes: ["BOWL_8OZ", "BOWL_16OZ", "FAMILY_32OZ"],
    allowSpiceCustomization: false,
    macros: { calories: 0, protein: 0, carbs: 0, fat: 0 },
    attributes: { richness: 72, umami: 0, aromatics: 88, spiceBase: 5 },
    pairings: ["Soothing Clean", "Sensitive Skin"],
  },
  {
    id: "rose",
    name: "Rose Soap",
    slug: "rose-soap",
    tagline: "With Rose Petals & Rose Essential Oil",
    description: "A beautifully scented soap for a luxurious bathing experience.",
    basePrice: 12.0,
    imageEmoji: "🌹",
    categoryId: "soap",
    dietaryTags: ["Organic"],
    availableSizes: ["BOWL_8OZ", "BOWL_16OZ", "FAMILY_32OZ"],
    allowSpiceCustomization: false,
    macros: { calories: 0, protein: 0, carbs: 0, fat: 0 },
    attributes: { richness: 83, umami: 0, aromatics: 98, spiceBase: 5 },
    pairings: ["Luxury Bath", "Floral Glow"],
  },
  {
    id: "brightening",
    name: "Brightening Soap",
    slug: "brightening-soap",
    tagline: "With Selected Botanical Ingredients",
    description: "Designed for a fresh and radiant-looking appearance.",
    basePrice: 11.0,
    imageEmoji: "✨",
    categoryId: "soap",
    dietaryTags: ["Organic"],
    availableSizes: ["BOWL_8OZ", "BOWL_16OZ", "FAMILY_32OZ"],
    allowSpiceCustomization: false,
    macros: { calories: 0, protein: 0, carbs: 0, fat: 0 },
    attributes: { richness: 74, umami: 0, aromatics: 92, spiceBase: 5 },
    pairings: ["Radiant Glow", "Daily Polish"],
  },
  {
    id: "beetroot",
    name: "Beetroot Soap",
    slug: "beetroot-soap",
    tagline: "With Beetroot Powder",
    description: "A naturally inspired soap for daily skincare.",
    basePrice: 10.5,
    imageEmoji: "❤️",
    categoryId: "soap",
    dietaryTags: ["Vegan"],
    availableSizes: ["BOWL_8OZ", "BOWL_16OZ", "FAMILY_32OZ"],
    allowSpiceCustomization: false,
    macros: { calories: 0, protein: 0, carbs: 0, fat: 0 },
    attributes: { richness: 76, umami: 0, aromatics: 87, spiceBase: 5 },
    pairings: ["Natural Care", "Daily Renewal"],
  },
  {
    id: "moroccan-blue",
    name: "Moroccan Blue Soap",
    slug: "moroccan-blue-soap",
    tagline: "With Mineral-Rich Clay",
    description: "Leaves the skin feeling clean and refreshed.",
    basePrice: 11.5,
    imageEmoji: "💙",
    categoryId: "soap",
    dietaryTags: ["Organic"],
    availableSizes: ["BOWL_8OZ", "BOWL_16OZ", "FAMILY_32OZ"],
    allowSpiceCustomization: false,
    macros: { calories: 0, protein: 0, carbs: 0, fat: 0 },
    attributes: { richness: 79, umami: 0, aromatics: 88, spiceBase: 5 },
    pairings: ["Mineral Cleanse", "Fresh Glow"],
  },
  {
    id: "honey",
    name: "Honey Soap",
    slug: "honey-soap",
    tagline: "With Pure Honey",
    description: "A moisturizing soap with a rich, creamy lather.",
    basePrice: 11.0,
    imageEmoji: "🍯",
    categoryId: "soap",
    dietaryTags: ["Gluten-Free"],
    availableSizes: ["BOWL_8OZ", "BOWL_16OZ", "FAMILY_32OZ"],
    allowSpiceCustomization: false,
    macros: { calories: 0, protein: 0, carbs: 0, fat: 0 },
    attributes: { richness: 82, umami: 0, aromatics: 90, spiceBase: 5 },
    pairings: ["Hydrating Lather", "Silky Skin"],
  },
];

export function getProduct(id: string) {
  return PRODUCTS.find((p) => p.id === id);
}

export function getCategory(id: string) {
  return CATEGORIES.find((c) => c.id === id);
}

export function calculateItemPrice(
  productId: string,
  size: PortionSize,
  addOns: SoupAddOn[]
): number {
  const product = getProduct(productId);
  if (!product) return 0;

  const basePrice = product.basePrice * SIZE_MULTIPLIERS[size];
  const addOnsPrice = addOns.reduce((sum, addOn) => sum + addOn.price, 0);

  return parseFloat((basePrice + addOnsPrice).toFixed(2));
}
